### ISSUE TITLE
swami_lightdm.py fails to parse lightdm.conf in Bodhi4.0 32 bit

### ISSUE THREAD

**Issue by rbtylee** [JeffHoogland/swami#3]
See [forum post](http://forums.bodhilinux.com/index.php?/topic/14013-swami-works-in-bodhi-40-64-bit-but-not-in-32-bit/) along with a tentative fix

**Comment by JeffHoogland** [comment]
Fixed via: https://github.com/JeffHoogland/swami/commit/67f5ca3e92f705766636951fcd6ad2866100a7cb
